#!/usr/bin/env php
<?php

require file_exists(__DIR__ . '/vendor/autoload.php') ? __DIR__ . '/vendor/autoload.php' : __DIR__ . '/../../autoload.php';

use Kayw\QualityHook\Command\RunCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new RunCommand());

$application->run();
